version: '3.9'
services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 'test123'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
volumes:
  mysql_data:

networks:
  mysql_network: