version: '3.9'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    restart: always
    shm_size: 2gb
    ports:
      - 4444:4444
    networks:
      - service-network

networks:
  service-network: